@startuml usecase-authentication
left to right direction
actor "Not logged User" as guest
actor "Logged User" as user 

rectangle Authentication {
  usecase "register to system" as register
  usecase "login to system" as login
  usecase "logout from system" as logout
}

guest --> register
guest --> login
user --> logout
logout ..> login : <<extend>>
login --> user

@enduml